version: '3.8'

services:
  spring:
    container_name: spring
    image: spring
    environment:
      - TZ=Asia/Seoul
    privileged: true
    networks:
      - aingle

networks:
  aingle:
    external: true
