services:
  nginx-react:
    container_name: nginx-react # 컨테이너 이름을 'nginx-react'로 설정
    image: nginx:alpine # 사용할 도커 이미지를 'nginx:alpine'으로 설정
    volumes:
      - /home/ubuntu/nginx-react:/etc/nginx/templates # 호스트의 '/home/ubuntu/templates-react' 디렉토리를 Nginx의 '/etc/nginx/templates' 디렉토리에 마운트
      - /home/ubuntu/nginx-react/logs:/var/log/nginx # 호스트의 '/home/ubuntu/nginx-react/logs' 디렉토리를 Nginx의 '/var/log/nginx' 디렉토리에 마운트
    networks:
      - aingle # 'aingle' 네트워크에 연결
    environment:
      - TZ=Asia/Seoul # 컨테이너 시간대를 'Asia/Seoul'로 설정

networks:
  aingle:
    external: true # 'aingle' 네트워크를 외부에서 생성된 네트워크로 설정