spring.config.import: optional:application-private.yml

server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: aingle-backend

springdoc:
  swagger-ui:
    path: ${swagger-url}

jwt:
  expiration_time: 3600000 #1시간
  secret: ${JWT}

kakao:
  grant-type: authorization_code
  client-id: ${kakao-client-id}
  redirect-uri: ${kakao-redirect-uri}

cloud:
  aws:
    s3:
      bucket: ${bucket-name}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${s3-access-key}
        secretKey: ${s3-secret-key}